DROP SCHEMA IF EXISTS unidb CASCADE;
CREATE SCHEMA unidb;

SET search_path = unidb, public;

DROP TABLE IF EXISTS universities;

CREATE TABLE universities (
	UNITID varchar(64) PRIMARY KEY,
	INSTNM varchar(300),
	ADDR varchar(100),
	CITY varchar(100),
	STABBR varchar(2),
	ZIP varchar(12),
	FIPS smallint,
	OBEREG smallint,
	CHFNM varchar(100),
	CHFTITLE varchar(100),
	GENTELE varchar(20),
	FAXTELE varchar(20),
	EIN varchar(20),
	OPEID varchar(20),
	OPEFLAG varchar(20),
	WEBADDR varchar(200),
	ADMINURL varchar(200),
	FAIDURL varchar(200),
	APPLURL varchar(200),
	NPRICURL varchar(200),
	SECTOR varchar(20),
	ICLEVEL varchar(20),
	CONTROL varchar(20),
	HLOFFER varchar(20),
	UGOFFER varchar(20),
	GROFFER varchar(20),
	HDEGOFR1 varchar(20),
	DEGGRANT varchar(20),
	HBCU varchar(20),
	HOSPITAL varchar(20),
	MEDICAL varchar(20),
	TRIBAL varchar(20),
	LOCALE varchar(20),
	OPENPUBL varchar(20),
	ACT varchar(20),
	NEWID varchar(20),
	DEATHYR varchar(20),
	CLOSEDAT varchar(20),
	CYACTIVE varchar(20),
	POSTSEC varchar(20),
	PSEFLAG varchar(20),
	PSET4FLG varchar(20),
	RPTMTH varchar(20),
	IALIAS varchar(1000),
	INSTCAT varchar(20),
	CCBASIC varchar(20),
	CCIPUG varchar(20),
	CCIPGRAD varchar(20),
	CCUGPROF varchar(20),
	CCENRPRF varchar(20),
	CCSIZSET varchar(20),
	CARNEGIE varchar(20),
	LANDGRNT varchar(20),
	INSTSIZE varchar(20),
	CBSA varchar(20),
	CBSATYPE varchar(20),
	CSA varchar(20),
	NECTA varchar(20),
	F1SYSTYP varchar(20),
	F1SYSNAM varchar(100),
	F1SYSCOD varchar(20),
	COUNTYCD varchar(20),
	COUNTYNM varchar(200),
	CNGDSTCD varchar(20),
	LONGITUD varchar(20),
	LATITUDE varchar(20)
);

\copy universities FROM '../unicsvtest/postscndryunivsrvy2013dirinfo.csv' WITH ( FORMAT CSV, HEADER, QUOTE '"', ENCODING 'LATIN1' ) ;
